// ItemNames.h - Director's Cut item names.
//
// GENERATED by tools/gen_dc_item_names.py - do not edit by hand.
#pragma once

#define DC_ITEM_NAME_COUNT 128

// The DC's item-name pointer table (SLUS_005.51 0x800901D8, indexed by
// itemId - 1 like the port's g_ItemNamePointers). The DC renames four ids -
// 0x04 -> BERETTA, 0x0D -> LOCKPICK (name only) and 0x31/0x32 -> MOON CREST -
// and every other name is identical to the USA build's.
extern const unsigned char* g_dcItemNamePointers[DC_ITEM_NAME_COUNT];
