// ItemDescriptions.h - Director's Cut item descriptions.
//
// GENERATED by tools/gen_dc_item_descriptions.py - do not edit by hand.
#pragma once

#define DC_ITEM_DESCRIPTION_COUNT 79

// The DC's item description table (SLUS_005.51 0x8008E9C6, indexed by
// itemId - 1 like the port's g_ItemDescriptions). Only a few entries differ
// from the USA build - item 0x04 is the Beretta M92FS "Custom edition" text
// and 0x31/0x32 are the MOON CREST halves.
extern unsigned char* g_dcItemDescriptions[DC_ITEM_DESCRIPTION_COUNT];
