# Generate the baked cellular wordmark and a preview of its exact TIM pixels.
# Run from the repository root. Add --preview to write tools/infested-title-preview.png.
# No external Python packages required.
from pathlib import Path
import argparse, math, random, struct, zlib
parser=argparse.ArgumentParser(description="Regenerate the active cellular subtitle and shadow textures.")
parser.add_argument("--preview", action="store_true", help="also write an enlarged PNG preview")
args=parser.parse_args()
STROKES = [(0.0, 2.0, 1.0, 13.0, 0.0), (0.0, 8.0, 0.0, 5.0, 18.0), (0.0, 0.0, 18.0, 11.0, 19.0), (1.0, 0.0, 19.0, 2.0, 0.0), (1.0, 2.0, 0.0, 15.0, 18.0), (1.0, 15.0, 18.0, 16.0, 0.0), (2.0, 2.0, 19.0, 3.0, 0.0), (2.0, 3.0, 0.0, 16.0, 1.0), (2.0, 2.0, 9.0, 13.0, 8.0), (3.0, 3.0, 1.0, 0.0, 19.0), (3.0, 3.0, 1.0, 15.0, 0.0), (3.0, 2.0, 9.0, 12.0, 10.0), (3.0, 0.0, 19.0, 15.0, 17.0), (4.0, 16.0, 1.0, 6.0, 0.0), (4.0, 6.0, 0.0, 1.0, 5.0), (4.0, 1.0, 5.0, 5.0, 9.0), (4.0, 5.0, 9.0, 13.0, 10.0), (4.0, 13.0, 10.0, 16.0, 14.0), (4.0, 16.0, 14.0, 12.0, 18.0), (4.0, 12.0, 18.0, 1.0, 17.0), (5.0, 0.0, 1.0, 17.0, 0.0), (5.0, 9.0, 0.0, 6.0, 19.0), (6.0, 3.0, 1.0, 0.0, 19.0), (6.0, 3.0, 1.0, 15.0, 0.0), (6.0, 2.0, 9.0, 12.0, 10.0), (6.0, 0.0, 19.0, 15.0, 17.0), (7.0, 1.0, 18.0, 3.0, 0.0), (7.0, 3.0, 0.0, 12.0, 2.0), (7.0, 12.0, 2.0, 17.0, 7.0), (7.0, 17.0, 7.0, 15.0, 14.0), (7.0, 15.0, 14.0, 9.0, 18.0), (7.0, 9.0, 18.0, 1.0, 18.0)]
W,H=176,36
base=[4,2,5,3,4,1,4,2];stretch=[.82,.91,.74,.86,.78,.96,.83,.88]
# Healthy red discs transition into hollow infected cells from left to right.
rng=random.Random(925)
segments=[];cells=[]
density=[0,.05,.2,.4,.7,.9,1,1]
for g,x0,y0,x1,y1 in STROKES:
 g=int(g)
 def xy(x,y):return ((7+g*19+x*.87+y*(-.10 if g%2 else .13))*1.1,(base[g]+y*stretch[g])*1.1)
 ax,ay=xy(x0,y0);bx,by=xy(x1,y1);segments.append((g,ax,ay,bx,by))
 steps=max(1,round(math.hypot(bx-ax,by-ay)/4.3))
 for i in range(steps+1):
  if rng.random()>density[g]:continue
  u=i/steps;cx=ax+(bx-ax)*u+rng.uniform(-.5,.5);cy=ay+(by-ay)*u+rng.uniform(-.5,.5)
  radius=rng.uniform(2.4,3.1)
  if any(math.hypot(cx-c[0],cy-c[1])<3.2 for c in cells):continue
  cells.append((cx,cy,radius))
# Extra hollow cells on separate N branches, and two on F.
for letter in (1,2):
 candidates=[seg for seg in segments if seg[0]==letter]
 if letter==1:
  for seg,u in ((candidates[0],.35),(candidates[2],.65)):
   g,ax,ay,bx,by=seg
   cells.append((ax+(bx-ax)*u,ay+(by-ay)*u,2.6))
  continue
 added=0
 for seg in candidates:
  g,ax,ay,bx,by=seg
  for u in (.3,.7,.5):
   cx=ax+(bx-ax)*u;cy=ay+(by-ay)*u
   if all(math.hypot(cx-c[0],cy-c[1])>3.5 for c in cells):
    cells.append((cx,cy,2.6));added+=1
    if added==2:break
  if added==2:break
healthy=[];healthy_rng=random.Random(178)
for g,ax,ay,bx,by in segments:
 if g>=6:continue
 steps=max(1,round(math.hypot(bx-ax,by-ay)/2.7))
 for i in range(steps+1):
  u=i/steps;cx=ax+(bx-ax)*u+healthy_rng.uniform(-.3,.3)
  cy=ay+(by-ay)*u+healthy_rng.uniform(-.3,.3)
  if all(math.hypot(cx-c[0],cy-c[1])>1.65 for c in healthy):
   healthy.append((cx,cy,healthy_rng.uniform(2.05,2.45)))

def dist(px,py,s):
 g,ax,ay,bx,by=s;dx,dy=bx-ax,by-ay
 t=max(0,min(1,((px-ax)*dx+(py-ay)*dy)/(dx*dx+dy*dy)))
 return math.hypot(px-ax-t*dx,py-ay-t*dy)
# Opaque black interiors plus a compact RGB555 palette for the hybrid image.
triples=[(0,0,0),(9,2,3),(13,2,3),(17,2,3),(19,3,4),(25,6,8)]
pal=[0,0x8000]+[(r|(g<<5)|(b<<10)) for r,g,b in triples[1:]]
pal+= [0]*(16-len(pal))
colors=[((p&31)*255//31,((p>>5)&31)*255//31,((p>>10)&31)*255//31) for p in pal]
indices=[]
for y in range(H):
 for x in range(W):
  px,py=x+.5,y+.5
  shade=0
  healthy_hits=[(math.hypot(px-cx,py-cy)/r,cx,cy,r) for cx,cy,r in healthy]
  if healthy_hits:
   dd,cx,cy,r=min(healthy_hits)
   if dd<=1:
    shade=3 if (1-dd)*r<.6 else 5
    if dd<.25:shade=4
  hits=[(math.hypot(px-cx,py-cy)/r,cx,cy,r) for cx,cy,r in cells]
  if hits:
   dd,cx,cy,r=min(hits)
   if dd<=1:
    shade=6 if (1-dd)*r<.85 else 1
    if x==int(cx-.4) and y==int(cy+.4):shade=2
  indices.append(shade)
pixels=bytes(indices[i]|(indices[i+1]<<4) for i in range(0,len(indices),2))
tim=struct.pack('<IIIHHHH',16,8,44,0,480,16,1)+struct.pack('<16H',*pal)+struct.pack('<IHHHH',12+len(pixels),0,0,W//4,H)+pixels
header=Path('src/game/InfestedTitleImage.h')
header.write_text('// Generated by tools/gen_infested_title.py; do not edit by hand.\n#pragma once\nalignas(4) static unsigned char kInfestedTitleTim[] = {\n'+''.join('    '+','.join(str(b) for b in tim[i:i+24])+',\n' for i in range(0,len(tim),24))+'};\n')
# Two dilation masks make a faint feathered black halo at runtime.
shadow_palette=[0,0x8000]+[0]*14
shadow_headers=[]
for layer,radius in enumerate((3,1)):
 mask=[]
 for y in range(H):
  for x in range(W):
   visible=any(0<=x+dx<W and 0<=y+dy<H and indices[(y+dy)*W+x+dx]
               for dy in range(-radius,radius+1) for dx in range(-radius,radius+1)
               if dx*dx+dy*dy<=radius*radius)
   mask.append(1 if visible else 0)
 data=bytes(mask[i]|mask[i+1]<<4 for i in range(0,len(mask),2))
 shadow=struct.pack('<IIIHHHH',16,8,44,0,480,16,1)+struct.pack('<16H',*shadow_palette)+struct.pack('<IHHHH',12+len(data),0,0,W//4,H)+data
 shadow_headers.append('alignas(4) static unsigned char kInfestedShadowTim'+str(layer)+'[] = {\n'+''.join('    '+','.join(str(b) for b in shadow[i:i+24])+',\n' for i in range(0,len(shadow),24))+'};\n')
with header.open('a') as f:f.write('\n'+''.join(shadow_headers))

def png(path,w,h,pixels):
 def chunk(t,d):return struct.pack('>I',len(d))+t+d+struct.pack('>I',zlib.crc32(t+d))
 raw=b''.join(b'\0'+bytes(pixels[y*w*3:(y+1)*w*3]) for y in range(h))
 path.write_bytes(b'\x89PNG\r\n\x1a\n'+chunk(b'IHDR',struct.pack('>IIBBBBB',w,h,8,2,0,0,0))+chunk(b'IDAT',zlib.compress(raw))+chunk(b'IEND',b''))
if args.preview:
 preview=[]
 for y in range(H*4):
  for x in range(W*4):
   idx=indices[(y//4)*W+x//4];preview.extend(colors[idx] if idx else (5,7,14))
 png(Path('tools/infested-title-preview.png'),W*4,H*4,preview)
